# Generated by Django 3.2.7 on 2021-12-17 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Theblog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title_tag',
            field=models.CharField(default='blog hub', max_length=255),
        ),
    ]
