# Generated by Django 3.2.7 on 2021-12-19 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Theblog', '0003_auto_20211217_1822'),
    ]

    operations = [
        migrations.CreateModel(
            name='category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
    ]
