# Generated by Django 4.1 on 2022-08-21 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='studentform',
            table='data',
        ),
    ]
